name: Test Automation REST API

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - all_tests
          - positive_tests
          - negative_tests

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
            
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run all tests
      if: github.event.inputs.deployment_target == 'all_tests'
      run: pytest    

    - name: Run positive tests
      if: github.event.inputs.deployment_target == 'positive_tests'
      run: pytest -m "positive"

    - name: Run negative tests
      if: github.event.inputs.deployment_target == 'negative_tests'
      run: pytest -m "negative"